substitutions:
  _IMAGE: us-central1-docker.pkg.dev/reelone-498406/killcam/tko-render-worker:latest

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - Dockerfile.worker
      - --tag
      - ${_IMAGE}
      - .

images:
  - ${_IMAGE}
