steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - BUILD_ID=${_BUILD_ID}
      - --tag
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
substitutions:
  _BUILD_ID: local
  _IMAGE: us-central1-docker.pkg.dev/reelone-498406/cloud-run-source-deploy/killcam:manual
